version: 2.1

jobs:
  build:
    docker:
    - image: cimg/base:stable
      user: circleci
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - run: mvn clean install
